resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: ldap-configmap
  files:
    - env.startup.txt

commonLabels:
  app: foo
  team: Beijing
commonAnnotations:
  application: foo
  owners: Xiaoming,Damao  